name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  equatable: ^2.0.3
  intl_utils: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  font_awesome_flutter: ^10.1.0
  mocktail: ^0.2.0
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/film_image/
flutter_intl:
  enabled: true


